version: '3'
services:
  laverie:
    build: ./Laverie
    network_mode : host
    ports: 
      - '8000:8000'
  homeassistant:
    container_name: Home-Assistant-Laverie
    image: homeassistant/home-assistant:latest
    volumes:
      - /run/dbus:/run/dbus:ro

    environment:
      - TZ=Europe/Sofia # get your Time Zone from - https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    network_mode: host
    ports:
      - '8123:8123'
    restart: always