# Generated by Django 4.2.7 on 2023-11-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='Numero_Machine',
            field=models.IntegerField(),
        ),
    ]
