# Generated by Django 4.2.7 on 2023-12-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_rename_transaction_status_machines_typemachine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machines',
            name='Active',
        ),
        migrations.AddField(
            model_name='machines',
            name='Disponible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='machines',
            name='Running',
            field=models.BooleanField(default=False),
        ),
    ]
