# Generated by Django 4.2.7 on 2023-12-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0014_locataire_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='SelectionDate',
            field=models.DateTimeField(null=True),
        ),
    ]
