version: '3'
services:
  laveriewebapp:
    image: laverie_webapp:latest
    container_name: laverie-webapp
    network_mode: host
    ports: 
      - '8000:8000'
  homeassistant:
    container_name: Home-Assistant-Laverie
    image: homeassistant/home-assistant:latest
    volumes:
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=Europe/Sofia 
    network_mode: host
    ports:
      - '8123:8123'
    restart: always