# Generated by Django 4.2.7 on 2023-12-20 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0003_rename_numero_capteur_machines_id_capteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataires',
            name='utilisateur',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Consomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Consomation', models.DateTimeField()),
                ('Duree_Consomation', models.IntegerField(null=True)),
                ('Energie_Consomee', models.IntegerField()),
                ('Utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.locataires')),
            ],
        ),
    ]
