# Generated by Django 4.2.7 on 2023-12-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_locataires_utilisateur_consomation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locataires',
            name='ID_Badge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
