# Generated by Django 4.2.7 on 2023-12-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_alter_locataires_id_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locataires',
            name='Nom',
        ),
        migrations.RemoveField(
            model_name='locataires',
            name='Prenom',
        ),
    ]
