# Generated by Django 4.2.7 on 2023-12-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_machines_transaction_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machines',
            old_name='transaction_status',
            new_name='TypeMachine',
        ),
    ]
