# Generated by Django 4.2.7 on 2023-12-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_remove_machines_active_machines_disponible_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machines',
            old_name='ID_Capteur',
            new_name='ID_Capteur_Button',
        ),
        migrations.AddField(
            model_name='machines',
            name='ID_Capteur_Current',
            field=models.CharField(default='sensor.sonoff_1001da0402_energy_day', max_length=255),
            preserve_default=False,
        ),
    ]
