# Generated by Django 4.2.7 on 2023-12-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_rename_id_capteur_button_machines_id_capteur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consomation',
            old_name='Energie_Consomee',
            new_name='comsumption',
        ),
        migrations.RenameField(
            model_name='consomation',
            old_name='Date_Consomation',
            new_name='comsumption_date',
        ),
        migrations.RenameField(
            model_name='consomation',
            old_name='Duree_Consomation',
            new_name='comsumption_duration',
        ),
        migrations.RenameField(
            model_name='consomation',
            old_name='Utilisateur',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='locataires',
            old_name='utilisateur',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='locataires',
            old_name='ID_Badge',
            new_name='user_badge_id',
        ),
        migrations.RenameField(
            model_name='machines',
            old_name='Disponible',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='machines',
            old_name='Numero_Machine',
            new_name='machine_id',
        ),
        migrations.RenameField(
            model_name='machines',
            old_name='Running',
            new_name='running',
        ),
        migrations.RenameField(
            model_name='machines',
            old_name='ID_Capteur',
            new_name='sensor_id',
        ),
        migrations.RenameField(
            model_name='machines',
            old_name='TypeMachine',
            new_name='typeMachine',
        ),
    ]
