# Generated by Django 4.2.7 on 2023-12-24 11:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0012_rename_energie_consomee_consomation_comsumption_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locataires',
            new_name='Locataire',
        ),
        migrations.RenameModel(
            old_name='Machines',
            new_name='Machine',
        ),
    ]
