# Generated by Django 4.2.7 on 2023-12-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0013_rename_locataires_locataire_rename_machines_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='permission',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=255),
        ),
    ]
