# Generated by Django 4.2.7 on 2024-02-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0016_consommation_remove_locataire_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommation',
            name='comsumption_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
