# Generated by Django 4.2.7 on 2023-11-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locataires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=255)),
                ('Prenom', models.CharField(max_length=255)),
                ('ID_Badge', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_Machine', models.IntegerField(max_length=8)),
                ('Active', models.BooleanField()),
                ('Numero_Capteur', models.CharField(max_length=255)),
            ],
        ),
    ]
